// USER LONGIN & REGISTER
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const COUNT_DOWN = "COUNT_DOWN";

// RESTAURANT VARIABLES
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";

// UPDATE PROFILE INFO
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_L_NAME = "CHANGE_L_NAME";
